// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/tools/get-app-overview.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/types.ts
var defaultRoutine = [
  { id: "r1", label: "Vakna och stiga upp", emoji: "\u2600\uFE0F" },
  { id: "r2", label: "\xC4tit frukost", emoji: "\u{1F963}" },
  { id: "r3", label: "Borstat t\xE4nderna", emoji: "\u{1FAA5}" },
  { id: "r4", label: "Tagit p\xE5 kl\xE4der", emoji: "\u{1F455}" },
  { id: "r5", label: "Packat skolv\xE4skan", emoji: "\u{1F392}" },
  { id: "r6", label: "P\xE5 v\xE4g till skolan", emoji: "\u{1F6B6}" }
];
var defaultEveningRoutine = [
  { id: "e1", label: "L\xE4gg fram kl\xE4der till imorgon", emoji: "\u{1F455}" },
  { id: "e2", label: "Packa skolv\xE4skan", emoji: "\u{1F392}" },
  { id: "e3", label: "Borsta t\xE4nderna", emoji: "\u{1FAA5}" },
  { id: "e4", label: "Duscha", emoji: "\u{1F6BF}" },
  { id: "e5", label: "L\xE4s en stund", emoji: "\u{1F4D6}" },
  { id: "e6", label: "L\xE4gg undan mobilen", emoji: "\u{1F4F1}" },
  { id: "e7", label: "G\xE5 och l\xE4gg dig", emoji: "\u{1F6CF}\uFE0F" }
];

// src/lib/mcp/tools/get-app-overview.ts
var SPECIES = [
  { id: "sun", label: "Sol" },
  { id: "fox", label: "R\xE4v" },
  { id: "panda", label: "Panda" },
  { id: "bunny", label: "Kanin" },
  { id: "cat", label: "Katt" },
  { id: "dog", label: "Labrador" },
  { id: "horse", label: "H\xE4st" },
  { id: "penguin", label: "Pingvin" },
  { id: "giraffe", label: "Giraff" }
];
var get_app_overview_default = defineTool({
  name: "get_app_overview",
  title: "Om appen",
  description: "F\xF6rklarar vad F\xF6ljis-appen \xE4r, vilka funktioner den har, hur F\xF6ljispo\xE4ng fungerar, vilka f\xF6ljis-arter som finns och vilka standardrutiner som f\xF6resl\xE5s f\xF6r morgon och kv\xE4ll.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const overview = {
      name: "F\xF6ljis",
      language: "sv",
      description: "En app som hj\xE4lper barn och unga att komma ig\xE5ng p\xE5 morgonen, landa p\xE5 kv\xE4llen, h\xE5lla koll p\xE5 sitt schema och checka in sitt m\xE5ende \u2013 med en egen f\xF6ljis (digital kompis) som f\xF6ljer med.",
      features: [
        "Morgonchecklista med egna punkter som kan flyttas i ordning",
        "Kv\xE4llschecklista med f\xF6rberedelser inf\xF6r n\xE4sta dag",
        "Schema med aktiviteter (lektioner, fotboll, musik m.m.) som kan betygs\xE4ttas r\xF6tt/gult/gr\xF6nt med kommentar",
        "M\xE5endecheck-in med k\xE4nslor och anteckning \u2013 kr\xE4vs innan morgon- och kv\xE4llsrutin",
        "Tips och r\xE5d anpassade f\xF6r skoldagen",
        "Achievements och F\xF6ljispo\xE4ng",
        "Aff\xE4r d\xE4r F\xF6ljispo\xE4ng byts mot tillbeh\xF6r och bakgrunder till f\xF6ljisen",
        "Sammanst\xE4llning (PDF) som eleven sj\xE4lv kan dela med v\xE5rdnadshavare eller mentor"
      ],
      points: {
        name: "F\xF6ljispo\xE4ng",
        earning: [
          "+5 per avbockad rutinpunkt (morgon och kv\xE4ll), +15 bonus n\xE4r hela rutinen \xE4r klar",
          "+10 f\xF6r en m\xE5endecheck-in",
          "+3 f\xF6r en genomf\xF6rd aktivitet, +1\u20132 extra f\xF6r betyget",
          "+2 f\xF6r ett l\xE4st tips",
          "+1 var femte klapp p\xE5 f\xF6ljisen"
        ],
        spending: "F\xF6ljispo\xE4ng anv\xE4nds i aff\xE4ren f\xF6r tillbeh\xF6r och bakgrunder."
      },
      companionSpecies: SPECIES,
      defaultMorningRoutine: defaultRoutine.map((r) => r.label),
      defaultEveningRoutine: defaultEveningRoutine.map((r) => r.label),
      dataStorage: "All elevdata lagras lokalt i elevens webbl\xE4sare (localStorage). Ingen personlig data finns tillg\xE4nglig via det h\xE4r MCP-gr\xE4nssnittet."
    };
    return {
      content: [{ type: "text", text: JSON.stringify(overview, null, 2) }],
      structuredContent: overview
    };
  }
});

// src/lib/mcp/tools/list-tips.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/tips.ts
var TIPS = [
  {
    id: "t1",
    category: "morgon",
    emoji: "\u{1F324}\uFE0F",
    title: "L\xE4gg fram kl\xE4der kv\xE4llen innan",
    body: "L\xE4gg fram dina kl\xE4der kv\xE4llen innan. D\xE5 blir morgonen mycket lugnare och du slipper leta."
  },
  {
    id: "t2",
    category: "morgon",
    emoji: "\u{1F963}",
    title: "N\xE5got litet i magen r\xE4cker",
    body: "kropp och knopp beh\xF6ver energi f\xF6r att orka dagen. Det beh\xF6ver inte vara n\xE5got stort, ett glas mj\xF6lk, en macka eller en banan funkar bra! Kan du inte \xE4ta p\xE5 morgonen - ta med mellis!"
  },
  {
    id: "t3",
    category: "morgon",
    emoji: "\u23F0",
    title: "5 minuters extra-marginal",
    body: "F\xF6rs\xF6k att st\xE4lla v\xE4ckaren 5 minuter tidigare. Lite extra tid g\xF6r hela skillnaden."
  },
  {
    id: "t4",
    category: "morgon",
    emoji: "\u{1F392}",
    title: "Packa v\xE4skan kv\xE4llen innan",
    body: "Kolla schemat och packa allt kv\xE4llen innan. P\xE5 morgonen beh\xF6ver du bara ta v\xE4skan och g\xE5."
  },
  {
    id: "t5",
    category: "skola",
    emoji: "\u{1F4AD}",
    title: "Det \xE4r okej att inte m\xE5 toppen",
    body: "Alla har dagar som k\xE4nns tunga. F\xF6rs\xF6k \xE4nd\xE5 att g\xE5 till skolan \u2013 ofta blir det l\xE4ttare n\xE4r du v\xE4l \xE4r d\xE4r."
  },
  {
    id: "t6",
    category: "skola",
    emoji: "\u{1F91D}",
    title: "Prata med n\xE5gon vuxen",
    body: "Om n\xE5got k\xE4nns jobbigt \u2013 ber\xE4tta f\xF6r en l\xE4rare, annan trygg vuxen eller n\xE5gon hemma. Du beh\xF6ver inte b\xE4ra det sj\xE4lv."
  },
  {
    id: "t7",
    category: "skola",
    emoji: "\u{1FA91}",
    title: "Hitta en lugn plats",
    body: "Om det blir f\xF6r mycket \u2013 fr\xE5ga om du f\xE5r g\xE5 ut en stund eller sitta i ett grupprum. Det \xE4r okej att beh\xF6va paus."
  },
  {
    id: "t8",
    category: "skola",
    emoji: "\u{1F4DD}",
    title: "Ett steg i taget",
    body: "T\xE4nk inte p\xE5 hela dagen. T\xE4nk bara: 'nu g\xE5r jag till f\xF6rsta lektionen'. Sen 'nu g\xE5r jag till rasten'."
  },
  {
    id: "t9",
    category: "andning",
    emoji: "\u{1FAC1}",
    title: "Fyrkantsandning",
    body: "Andas in 4 sekunder, h\xE5ll 4, andas ut 4, h\xE5ll 4. G\xF6r det fyra g\xE5nger. Det lugnar kroppen snabbt."
  },
  {
    id: "t10",
    category: "andning",
    emoji: "\u{1F32C}\uFE0F",
    title: "L\xE5nga utandningar",
    body: "Andas in genom n\xE4san i 4 sek och ut genom munnen i 6 sek. Det skickar en lugnande signal till hj\xE4rnan."
  },
  {
    id: "t11",
    category: "andning",
    emoji: "\u{1F590}\uFE0F",
    title: "Handandning",
    body: "Spreta ut fingrarna. Dra l\xE5ngsamt ett finger l\xE4ngs varje finger \u2013 andas in upp, andas ut ner."
  },
  {
    id: "t12",
    category: "social",
    emoji: "\u{1F44B}",
    title: "S\xE4g bara 'hej'",
    body: "Du beh\xF6ver inte ha en l\xE5ng konversation. Ett 'hej' eller leende r\xE4cker som start."
  },
  {
    id: "t13",
    category: "social",
    emoji: "\u{1FAC2}",
    title: "Du \xE4r inte ensam",
    body: "M\xE5nga k\xE4nner sig nerv\xF6sa i sociala situationer \u2013 \xE4ven de som verkar trygga. Det \xE4r helt normalt."
  },
  {
    id: "t14",
    category: "social",
    emoji: "\u2753",
    title: "St\xE4ll en fr\xE5ga",
    body: "Att fr\xE5ga n\xE5gon n\xE5got (\xE4ven enkelt) \xE4r ett bra s\xE4tt att b\xF6rja prata. De flesta gillar att hj\xE4lpa till."
  },
  {
    id: "t15",
    category: "fokus",
    emoji: "\u{1F3AF}",
    title: "10 minuter i taget",
    body: "S\xE4tt en timer p\xE5 10 minuter och jobba bara d\xE5. Sen paus. Det \xE4r mycket l\xE4ttare att b\xF6rja n\xE4r det \xE4r kort."
  },
  {
    id: "t16",
    category: "fokus",
    emoji: "\u{1F4F5}",
    title: "L\xE4gg undan mobilen",
    body: "L\xE4gg mobilen i ett annat rum medan du pluggar. Hj\xE4rnan blir lugnare n\xE4r den inte v\xE4ntar p\xE5 notiser."
  },
  {
    id: "t17",
    category: "fokus",
    emoji: "\u{1F4A7}",
    title: "Vatten och r\xF6relse",
    body: "Drick vatten och r\xF6r p\xE5 dig 2 minuter. Det v\xE4cker hj\xE4rnan b\xE4ttre \xE4n att stirra p\xE5 boken."
  },
  {
    id: "t18",
    category: "fokus",
    emoji: "\u{1F4CB}",
    title: "Skriv en lista",
    body: "Skriv ner allt du \xF6nskar g\xF6ra. Bocka av en sak i taget. Det blir tydligare och du k\xE4nner dig klokare."
  },
  // Kvällstips
  {
    id: "t19",
    category: "kvall",
    emoji: "\u{1F319}",
    title: "Kv\xE4llsrutin g\xF6r morgonen l\xE4ttare",
    body: "Att g\xF6ra samma saker i samma ordning varje kv\xE4ll lugnar hj\xE4rnan och hj\xE4lper dig somna."
  },
  {
    id: "t20",
    category: "kvall",
    emoji: "\u{1F455}",
    title: "L\xE4gg fram allt redan ikv\xE4ll",
    body: "Kl\xE4der, v\xE4ska, vattenflaska \u2013 st\xE4ll fram det vid d\xF6rren. D\xE5 blir morgonen n\xE4stan automatisk."
  },
  {
    id: "t21",
    category: "kvall",
    emoji: "\u{1F4F5}",
    title: "Sk\xE4rmpaus en timme innan",
    body: "L\xE4gg undan mobilen ungef\xE4r en timme innan du ska sova. Hj\xE4rnan f\xE5r d\xE5 l\xE4ttare att varva ner."
  },
  {
    id: "t22",
    category: "kvall",
    emoji: "\u{1F4D4}",
    title: "Skriv av dig",
    body: "Skriv ner tre saker som var bra idag och en sak du ser fram emot. Det g\xF6r tankarna lugnare innan s\xE4ngen."
  },
  {
    id: "t23",
    category: "kvall",
    emoji: "\u{1F6C1}",
    title: "Varmt = s\xF6mnigt",
    body: "Ett varmt bad eller dusch p\xE5 kv\xE4llen hj\xE4lper kroppen att slappna av och bli redo f\xF6r s\xF6mn."
  },
  // Sömn
  {
    id: "t24",
    category: "s\xF6mn",
    emoji: "\u{1F6CF}\uFE0F",
    title: "Samma tid varje kv\xE4ll",
    body: "F\xF6rs\xF6k g\xE5 och l\xE4gga dig ungef\xE4r samma tid varje dag \u2013 \xE4ven p\xE5 helger. Kroppen \xE4lskar rytm."
  },
  {
    id: "t25",
    category: "s\xF6mn",
    emoji: "\u{1F311}",
    title: "M\xF6rkt och svalt",
    body: "Ett svalt och g\xE4rna ganska m\xF6rkt rum hj\xE4lper dig sova djupare. Dra f\xF6r gardinerna och v\xE4dra en stund. En nattlampa kan ocks\xE5 vara bra att ha!"
  },
  {
    id: "t26",
    category: "s\xF6mn",
    emoji: "\u{1F411}",
    title: "Tankarna snurrar?",
    body: "R\xE4kna l\xE5ngsamt bakl\xE4nges fr\xE5n 100. Det ger hj\xE4rnan n\xE5got tr\xE5kigt att g\xF6ra s\xE5 du somnar l\xE4ttare."
  },
  // Kropp & rörelse
  {
    id: "t27",
    category: "kropp",
    emoji: "\u{1F6B6}",
    title: "G\xE5 en kort runda",
    body: "Bara 10 minuters promenad g\xF6r skillnad f\xF6r hum\xF6ret. Du beh\xF6ver inte tr\xE4na h\xE5rt."
  },
  {
    id: "t28",
    category: "kropp",
    emoji: "\u{1F938}",
    title: "Stretcha 2 minuter",
    body: "Str\xE4ck armarna mot taket, rulla axlarna, b\xF6j dig fram\xE5t. Kroppen blir piggare p\xE5 sekunder."
  },
  {
    id: "t29",
    category: "kropp",
    emoji: "\u{1F483}",
    title: "En l\xE5t = ett pass",
    body: "S\xE4tt p\xE5 din favoritl\xE5t och dansa loss. Tre minuters r\xF6relse h\xF6jer hum\xF6ret rej\xE4lt."
  },
  {
    id: "t30",
    category: "kropp",
    emoji: "\u{1F964}",
    title: "Drick vatten ofta",
    body: "Hj\xE4rnan jobbar mycket b\xE4ttre n\xE4r du \xE4r pigg och hydrerad. Ta ett glas vatten nu."
  },
  // Fler skola/social/andning
  {
    id: "t31",
    category: "skola",
    emoji: "\u{1F3A7}",
    title: "H\xF6rlurar som lugn",
    body: "Lugn musik eller brus i h\xF6rlurarna kan hj\xE4lpa n\xE4r det \xE4r r\xF6rigt runt omkring."
  },
  {
    id: "t32",
    category: "social",
    emoji: "\u{1F4AC}",
    title: "Texta f\xF6rst",
    body: "Att skicka ett kort meddelande \xE4r ofta l\xE4ttare \xE4n att prata. Det r\xE4knas ocks\xE5!"
  },
  {
    id: "t33",
    category: "andning",
    emoji: "\u{1F30A}",
    title: "V\xE5gandning",
    body: "T\xE4nk dig en v\xE5g som rullar in n\xE4r du andas in och ut n\xE4r du andas ut. G\xF6r det 5 g\xE5nger."
  },
  {
    id: "t34",
    category: "morgon",
    emoji: "\u{1F3B5}",
    title: "Morgonl\xE5t",
    body: "Spela en l\xE5t du gillar direkt n\xE4r du vaknar. Den ger kroppen energi att komma ig\xE5ng."
  }
];
var TIP_CATEGORIES = {
  morgon: { label: "Klara morgonen", emoji: "\u{1F305}", gradient: "gradient-sunrise" },
  kvall: { label: "Lugn kv\xE4ll", emoji: "\u{1F319}", gradient: "gradient-sky" },
  s\u00F6mn: { label: "Sova b\xE4ttre", emoji: "\u{1F4A4}", gradient: "gradient-calm" },
  skola: { label: "N\xE4r det k\xE4nns jobbigt", emoji: "\u{1F327}\uFE0F", gradient: "gradient-sky" },
  andning: { label: "Andnings\xF6vningar", emoji: "\u{1FAC1}", gradient: "gradient-calm" },
  social: { label: "Sociala situationer", emoji: "\u{1F44B}", gradient: "gradient-sky" },
  fokus: { label: "Fokus & l\xE4xor", emoji: "\u{1F3AF}", gradient: "gradient-sunrise" },
  kropp: { label: "Kropp & r\xF6relse", emoji: "\u{1F4AA}", gradient: "gradient-sunrise" }
};
var COPING_BY_FEELING = {
  glad: ["t12"],
  lugn: ["t10"],
  stolt: ["t12"],
  tacksam: ["t10"],
  tr\u00F6tt: ["t17", "t3", "t2"],
  okoncentrerad: ["t15", "t16", "t18"],
  uttr\u00E5kad: ["t15", "t17"],
  orolig: ["t9", "t10", "t11"],
  nerv\u00F6s: ["t9", "t13", "t11"],
  stressad: ["t9", "t10", "t8"],
  ledsen: ["t6", "t5", "t7"],
  ensam: ["t13", "t12", "t14"],
  besviken: ["t5", "t6"],
  arg: ["t9", "t10", "t11"],
  frustrerad: ["t9", "t8", "t7"]
};
var FEELINGS = [
  { value: "glad", emoji: "\u{1F604}", group: "H\xE4rliga" },
  { value: "lugn", emoji: "\u{1F60C}", group: "H\xE4rliga" },
  { value: "stolt", emoji: "\u{1F60E}", group: "H\xE4rliga" },
  { value: "tacksam", emoji: "\u{1F970}", group: "H\xE4rliga" },
  { value: "tr\xF6tt", emoji: "\u{1F634}", group: "L\xE5gt energil\xE4ge" },
  { value: "okoncentrerad", emoji: "\u{1F300}", group: "L\xE5gt energil\xE4ge" },
  { value: "uttr\xE5kad", emoji: "\u{1F610}", group: "L\xE5gt energil\xE4ge" },
  { value: "orolig", emoji: "\u{1F61F}", group: "Oroliga" },
  { value: "nerv\xF6s", emoji: "\u{1F62C}", group: "Oroliga" },
  { value: "stressad", emoji: "\u{1F635}", group: "Oroliga" },
  { value: "ledsen", emoji: "\u{1F622}", group: "Tunga" },
  { value: "ensam", emoji: "\u{1F97A}", group: "Tunga" },
  { value: "besviken", emoji: "\u{1F614}", group: "Tunga" },
  { value: "arg", emoji: "\u{1F620}", group: "Heta" },
  { value: "frustrerad", emoji: "\u{1F624}", group: "Heta" }
];

// src/lib/mcp/tools/list-tips.ts
var list_tips_default = defineTool2({
  name: "list_tips",
  title: "Lista tips och r\xE5d",
  description: "Lista F\xF6ljis-appens tips och r\xE5d f\xF6r barn (morgon, skola, andning, social, fokus, kv\xE4ll, s\xF6mn, kropp). Filtrera p\xE5 kategori eller s\xF6kord.",
  inputSchema: {
    category: z.enum(["morgon", "skola", "andning", "social", "fokus", "kvall", "s\xF6mn", "kropp"]).optional().describe("Begr\xE4nsa till en kategori."),
    query: z.string().optional().describe("Fritexts\xF6kning i titel och text.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category, query }) => {
    const q = query?.toLowerCase();
    const tips = TIPS.filter(
      (t) => (!category || t.category === category) && (!q || t.title.toLowerCase().includes(q) || t.body.toLowerCase().includes(q))
    ).map((t) => ({
      id: t.id,
      category: t.category,
      categoryLabel: TIP_CATEGORIES[t.category]?.label ?? t.category,
      title: t.title,
      body: t.body
    }));
    return {
      content: [
        {
          type: "text",
          text: tips.length ? tips.map((t) => `[${t.categoryLabel}] ${t.title}
${t.body}`).join("\n\n") : "Inga tips matchade s\xF6kningen."
        }
      ],
      structuredContent: { count: tips.length, tips }
    };
  }
});

// src/lib/mcp/tools/list-achievements.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/achievements.ts
var ACHIEVEMENTS = [
  {
    id: "first-step",
    title: "F\xF6rsta steget",
    description: "Du har b\xF6rjat din resa!",
    hint: "Kom ig\xE5ng med appen",
    icon: "\u{1F331}",
    check: (s) => s.points >= 1
  },
  {
    id: "morning-hero",
    title: "Morgonhj\xE4lte",
    description: "Klarat hela morgonrutinen en dag",
    hint: "Bocka av allt p\xE5 morgonchecklistan",
    icon: "\u2600\uFE0F",
    check: (s) => s.routineHistory.some((h) => h.itemIds.length >= s.routine.length && s.routine.length > 0)
  },
  {
    id: "morning-week",
    title: "Veckans morgon",
    description: "5 morgnar i rad med full checklista",
    hint: "Klara morgonrutinen 5 dagar i rad",
    icon: "\u{1F305}",
    check: (s) => {
      const sorted = [...s.routineHistory].sort((a, b) => a.date.localeCompare(b.date));
      let streak = 0;
      let last = null;
      for (const h of sorted) {
        if (h.itemIds.length < s.routine.length || s.routine.length === 0) {
          streak = 0;
          last = h.date;
          continue;
        }
        if (last) {
          const d = new Date(last);
          d.setDate(d.getDate() + 1);
          const expected = d.toISOString().slice(0, 10);
          streak = h.date === expected ? streak + 1 : 1;
        } else streak = 1;
        last = h.date;
        if (streak >= 5) return true;
      }
      return false;
    }
  },
  {
    id: "mood-5",
    title: "Lyssnar p\xE5 sig sj\xE4lv",
    description: "5 m\xE5ende-incheckningar",
    hint: "Checka in ditt m\xE5ende flera g\xE5nger",
    icon: "\u{1F49B}",
    check: (s) => s.moodEntries.length >= 5
  },
  {
    id: "mood-20",
    title: "K\xE4nslospanare",
    description: "20 m\xE5ende-incheckningar",
    hint: "Forts\xE4tt checka in ditt m\xE5ende",
    icon: "\u{1F52E}",
    check: (s) => s.moodEntries.length >= 20
  },
  {
    id: "streak-3",
    title: "Tre i rad",
    description: "3 dagars streak!",
    hint: "Anv\xE4nd appen flera dagar i rad",
    icon: "\u2728",
    check: (s) => s.streak >= 3
  },
  {
    id: "streak-7",
    title: "Veckok\xE4mpe",
    description: "7 dagars streak!",
    hint: "En hel vecka i rad",
    icon: "\u{1F525}",
    check: (s) => s.streak >= 7
  },
  {
    id: "streak-30",
    title: "M\xE5nadens stj\xE4rna",
    description: "30 dagar i rad \u2013 wow!",
    hint: "En hel m\xE5nad i rad",
    icon: "\u{1F31F}",
    check: (s) => s.streak >= 30
  },
  {
    id: "schedule-built",
    title: "Strukturerad",
    description: "Du har lagt in ditt schema",
    hint: "L\xE4gg till lektioner i schemat",
    icon: "\u{1F4C5}",
    check: (s) => s.schedule.length >= 3
  },
  {
    id: "tip-explorer",
    title: "Nyfiken",
    description: "L\xE4st 5 tips",
    hint: "Utforska tipsbiblioteket",
    icon: "\u{1F9ED}",
    check: (s) => s.readTips.length >= 5
  },
  {
    id: "tip-master",
    title: "Tipsm\xE4stare",
    description: "L\xE4st 15 tips",
    hint: "Forts\xE4tt utforska tips",
    icon: "\u{1F4DA}",
    check: (s) => s.readTips.length >= 15
  },
  {
    id: "evening-hero",
    title: "Kv\xE4llshj\xE4lte",
    description: "Klarat hela kv\xE4llsrutinen en dag",
    hint: "Bocka av allt p\xE5 kv\xE4llschecklistan",
    icon: "\u{1F319}",
    check: (s) => s.eveningHistory.some((h) => h.itemIds.length >= s.eveningRoutine.length && s.eveningRoutine.length > 0)
  },
  {
    id: "evening-week",
    title: "Lugna kv\xE4llar",
    description: "5 kv\xE4llar med full checklista",
    hint: "Klara kv\xE4llsrutinen 5 g\xE5nger",
    icon: "\u{1F31C}",
    check: (s) => s.eveningHistory.filter((h) => h.itemIds.length >= s.eveningRoutine.length && s.eveningRoutine.length > 0).length >= 5
  },
  {
    id: "full-day",
    title: "Hela dagen klar",
    description: "Morgon- och kv\xE4llsrutin samma dag",
    hint: "Klara b\xE5da rutinerna p\xE5 samma dag",
    icon: "\u{1F317}",
    check: (s) => {
      if (s.routine.length === 0 || s.eveningRoutine.length === 0) return false;
      return s.routineHistory.some(
        (m) => m.itemIds.length >= s.routine.length && s.eveningHistory.some((e) => e.date === m.date && e.itemIds.length >= s.eveningRoutine.length)
      );
    }
  },
  {
    id: "rating-first",
    title: "Hur k\xE4ndes det?",
    description: "Ditt f\xF6rsta aktivitetsbetyg",
    hint: "Bed\xF6m hur en aktivitet k\xE4ndes",
    icon: "\u{1F3AD}",
    check: (s) => s.lessonCompletions.some((c) => !!c.rating)
  },
  {
    id: "rating-good-5",
    title: "Bra dag-samlare",
    description: "5 aktiviteter som k\xE4ndes bra",
    hint: "Markera 'Bra' p\xE5 flera aktiviteter",
    icon: "\u{1F308}",
    check: (s) => s.lessonCompletions.filter((c) => c.rating === "good").length >= 5
  },
  {
    id: "honest-feeler",
    title: "\xC4rlig med k\xE4nslor",
    description: "Anv\xE4nt alla tre betyg minst en g\xE5ng",
    hint: "Prova r\xF6d, gul och gr\xF6n",
    icon: "\u{1F3A8}",
    check: (s) => s.lessonCompletions.some((c) => c.rating === "bad") && s.lessonCompletions.some((c) => c.rating === "ok") && s.lessonCompletions.some((c) => c.rating === "good")
  },
  {
    id: "companion-named",
    title: "B\xE4sta v\xE4nner",
    description: "Du har valt din f\xF6ljis",
    hint: "V\xE4lj och namnge en f\xF6ljis",
    icon: "\u{1FAC2}",
    check: (s) => s.onboardingDone
  },
  {
    id: "petting-pro",
    title: "Mjukis",
    description: "Klappat din f\xF6ljis 25 g\xE5nger",
    hint: "Klicka och dra \xF6ver din f\xF6ljis",
    icon: "\u{1F495}",
    check: (s) => s.pettingCount >= 25
  },
  {
    id: "points-100",
    title: "100-klubben",
    description: "Samlat 100 F\xF6ljispo\xE4ng",
    hint: "Samla F\xF6ljispo\xE4ng genom att anv\xE4nda appen",
    icon: "\u{1F4AF}",
    check: (s) => s.points >= 100
  },
  {
    id: "points-500",
    title: "Stj\xE4rnsamlare",
    description: "500 F\xF6ljispo\xE4ng \u2013 fantastiskt!",
    hint: "Forts\xE4tt samla F\xF6ljispo\xE4ng",
    icon: "\u2B50",
    check: (s) => s.points >= 500
  }
];

// src/lib/mcp/tools/list-achievements.ts
var list_achievements_default = defineTool3({
  name: "list_achievements",
  title: "Lista achievements",
  description: "Lista alla achievements som g\xE5r att l\xE5sa upp i F\xF6ljis-appen, med titel, beskrivning och tips om hur man l\xE5ser upp dem.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const achievements = ACHIEVEMENTS.map((a) => ({
      id: a.id,
      title: a.title,
      description: a.description,
      hint: a.hint
    }));
    return {
      content: [
        {
          type: "text",
          text: achievements.map((a) => `${a.title} \u2013 ${a.description} (${a.hint})`).join("\n")
        }
      ],
      structuredContent: { count: achievements.length, achievements }
    };
  }
});

// src/lib/mcp/tools/list-shop-items.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z2 } from "npm:zod@^4.4.3";

// src/lib/shop.ts
var SHOP_ITEMS = [
  // ---------- Tillbehör / kläder ----------
  { id: "acc_hat", category: "accessory", name: "Spetsig hatt", description: "En klassisk festhatt p\xE5 toppen", emoji: "\u{1F3A9}", price: 100 },
  { id: "acc_party", category: "accessory", name: "Festhatt", description: "Konformad partyhatt", emoji: "\u{1F973}", price: 120 },
  { id: "acc_glasses", category: "accessory", name: "Solglas\xF6gon", description: "Coola solglas\xF6gon", emoji: "\u{1F576}\uFE0F", price: 150 },
  { id: "acc_bow", category: "accessory", name: "Rosett", description: "S\xF6t rosett p\xE5 huvudet", emoji: "\u{1F380}", price: 130 },
  { id: "acc_scarf", category: "accessory", name: "Halsduk", description: "Mysig stickad halsduk", emoji: "\u{1F9E3}", price: 180 },
  { id: "acc_crown", category: "accessory", name: "Krona", description: "Gyllene krona f\xF6r en kunglig f\xF6ljis", emoji: "\u{1F451}", price: 350 },
  { id: "acc_flower", category: "accessory", name: "Blomma", description: "Liten blomma bakom \xF6rat", emoji: "\u{1F338}", price: 90 },
  { id: "acc_headphones", category: "accessory", name: "H\xF6rlurar", description: "Stora bekv\xE4ma h\xF6rlurar", emoji: "\u{1F3A7}", price: 220 },
  { id: "acc_cap", category: "accessory", name: "Keps", description: "Sportig keps", emoji: "\u{1F9E2}", price: 160 },
  { id: "acc_wizard", category: "accessory", name: "Trollkarlshatt", description: "Magisk hatt med stj\xE4rnor", emoji: "\u{1F9D9}", price: 400 },
  { id: "acc_glasses_round", category: "accessory", name: "Runda glas\xF6gon", description: "Smarta runda glas\xF6gon", emoji: "\u{1F453}", price: 140 },
  { id: "acc_tophat", category: "accessory", name: "H\xF6g hatt", description: "Elegant h\xF6g cylinderhatt", emoji: "\u{1F3A9}", price: 260 },
  { id: "acc_beret", category: "accessory", name: "Basker", description: "Konstn\xE4rlig basker", emoji: "\u{1F3A8}", price: 170 },
  { id: "acc_tiara", category: "accessory", name: "Diadem", description: "Glittrigt diadem med \xE4delstenar", emoji: "\u{1F48E}", price: 320 },
  { id: "acc_santa", category: "accessory", name: "Tomtem\xF6ssa", description: "R\xF6d och vit tomtem\xF6ssa", emoji: "\u{1F385}", price: 200 },
  { id: "acc_helmet", category: "accessory", name: "Riddarhj\xE4lm", description: "Skinande riddarhj\xE4lm", emoji: "\u26D1\uFE0F", price: 240 },
  { id: "acc_pirate", category: "accessory", name: "Piratlapp", description: "Svart \xF6gonlapp f\xF6r pirater", emoji: "\u{1F3F4}\u200D\u2620\uFE0F", price: 190 },
  { id: "acc_glasses_3d", category: "accessory", name: "Trekantiga glas\xF6gon", description: "Glas\xF6gon i trekantsform", emoji: "\u{1F53A}", price: 210 },
  { id: "acc_antlers", category: "accessory", name: "Renhorn", description: "Mysiga horn f\xF6r julst\xE4mning", emoji: "\u{1F98C}", price: 230 },
  { id: "acc_butterfly", category: "accessory", name: "Fj\xE4ril", description: "Fj\xE4ril som landat p\xE5 huvudet", emoji: "\u{1F98B}", price: 150 },
  { id: "acc_leaf", category: "accessory", name: "H\xF6stl\xF6v", description: "Litet l\xF6v p\xE5 \xF6rat", emoji: "\u{1F341}", price: 80 },
  // ---------- Bakgrunder ----------
  { id: "bg_meadow", category: "background", name: "Blomster\xE4ng", description: "Solig \xE4ng med blommor", emoji: "\u{1F33C}", price: 200 },
  { id: "bg_beach", category: "background", name: "Strand", description: "Sand, hav och solnedg\xE5ng", emoji: "\u{1F3D6}\uFE0F", price: 250 },
  { id: "bg_space", category: "background", name: "Rymden", description: "Stj\xE4rnor och planeter", emoji: "\u{1F30C}", price: 350 },
  { id: "bg_forest", category: "background", name: "Skog", description: "Lugn skog med tr\xE4dtoppar", emoji: "\u{1F332}", price: 220 },
  { id: "bg_night", category: "background", name: "Stj\xE4rnhimmel", description: "M\xF6rk himmel med m\xE5nsken", emoji: "\u{1F319}", price: 280 },
  { id: "bg_rainbow", category: "background", name: "Regnb\xE5ge", description: "F\xE4rgglad regnb\xE5ge", emoji: "\u{1F308}", price: 320 },
  { id: "bg_mountain", category: "background", name: "Berg", description: "Sn\xF6kl\xE4dda bergstoppar", emoji: "\u26F0\uFE0F", price: 270 },
  { id: "bg_ocean", category: "background", name: "Hav", description: "Djupbl\xE5tt hav med v\xE5gor", emoji: "\u{1F30A}", price: 240 },
  { id: "bg_city", category: "background", name: "Stad", description: "Stadssilhuett i skymning", emoji: "\u{1F3D9}\uFE0F", price: 290 },
  { id: "bg_aurora", category: "background", name: "Norrsken", description: "Magiskt norrsken p\xE5 natthimlen", emoji: "\u2728", price: 380 },
  { id: "bg_sunrise", category: "background", name: "Soluppg\xE5ng", description: "Mjuka morgonf\xE4rger", emoji: "\u{1F305}", price: 230 },
  { id: "bg_sakura", category: "background", name: "K\xF6rsb\xE4rsblom", description: "Rosa k\xF6rsb\xE4rsblommor", emoji: "\u{1F338}", price: 260 },
  { id: "bg_winter", category: "background", name: "Vinterland", description: "Sn\xF6t\xE4ckt landskap", emoji: "\u2744\uFE0F", price: 250 },
  { id: "bg_garden", category: "background", name: "Tr\xE4dg\xE5rd", description: "Frodig tr\xE4dg\xE5rd med blommor", emoji: "\u{1F33A}", price: 220 },
  { id: "bg_clouds", category: "background", name: "Molnhimmel", description: "Mjuka moln p\xE5 bl\xE5 himmel", emoji: "\u2601\uFE0F", price: 180 },
  { id: "bg_underwater", category: "background", name: "Under vattnet", description: "Korallrev med fiskar", emoji: "\u{1F420}", price: 310 }
];
var SHOP_CATEGORIES = [
  { id: "accessory", label: "Tillbeh\xF6r", emoji: "\u{1F3A9}", description: "Hattar, glas\xF6gon och kl\xE4der till din f\xF6ljis" },
  { id: "background", label: "Bakgrunder", emoji: "\u{1F30C}", description: "Scener bakom din f\xF6ljis" }
];

// src/lib/mcp/tools/list-shop-items.ts
var list_shop_items_default = defineTool4({
  name: "list_shop_items",
  title: "Lista aff\xE4rens sortiment",
  description: "Lista allt som g\xE5r att k\xF6pa med F\xF6ljispo\xE4ng i appens aff\xE4r: tillbeh\xF6r/kl\xE4der och bakgrunder, med pris.",
  inputSchema: {
    category: z2.enum(["accessory", "background"]).optional().describe("Begr\xE4nsa till tillbeh\xF6r eller bakgrunder."),
    maxPrice: z2.number().optional().describe("Visa bara saker som kostar h\xF6gst s\xE5 m\xE5nga F\xF6ljispo\xE4ng.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category, maxPrice }) => {
    const labels = Object.fromEntries(SHOP_CATEGORIES.map((c) => [c.id, c.label]));
    const items = SHOP_ITEMS.filter(
      (i) => (!category || i.category === category) && (maxPrice == null || i.price <= maxPrice)
    ).map((i) => ({
      id: i.id,
      category: i.category,
      categoryLabel: labels[i.category] ?? i.category,
      name: i.name,
      description: i.description,
      price: i.price
    }));
    return {
      content: [
        {
          type: "text",
          text: items.length ? items.map((i) => `${i.name} (${i.categoryLabel}) \u2013 ${i.price} F\xF6ljispo\xE4ng: ${i.description}`).join("\n") : "Inget i aff\xE4ren matchade filtret."
        }
      ],
      structuredContent: { count: items.length, items }
    };
  }
});

// src/lib/mcp/tools/suggest-coping.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z3 } from "npm:zod@^4.4.3";
var feelings = FEELINGS.map((f) => f.value);
var suggest_coping_default = defineTool5({
  name: "suggest_coping",
  title: "F\xF6rslag utifr\xE5n k\xE4nsla",
  description: "Ge appens konkreta f\xF6rslag p\xE5 vad man kan g\xF6ra n\xE4r man k\xE4nner en viss k\xE4nsla (t.ex. stressad, ledsen, okoncentrerad).",
  inputSchema: {
    feeling: z3.enum(feelings).describe("K\xE4nslan som f\xF6rslagen ska matcha.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ feeling }) => {
    const suggestions = COPING_BY_FEELING[feeling] ?? [];
    return {
      content: [
        {
          type: "text",
          text: suggestions.length ? `N\xE4r man k\xE4nner sig ${feeling}:
- ${suggestions.join("\n- ")}` : `Inga f\xF6rslag finns f\xF6r k\xE4nslan ${feeling}.`
        }
      ],
      structuredContent: { feeling, suggestions }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "foljis-mcp",
  title: "F\xF6ljis",
  version: "0.1.0",
  instructions: "Verktyg f\xF6r F\xF6ljis \u2013 en svensk app som hj\xE4lper barn med morgon- och kv\xE4llsrutiner, schema, m\xE5ende och en digital kompis (f\xF6ljis). Anv\xE4nd get_app_overview f\xF6r att f\xF6rst\xE5 appen, list_tips f\xF6r tips och r\xE5d, suggest_coping f\xF6r f\xF6rslag utifr\xE5n en k\xE4nsla, list_achievements f\xF6r achievements och list_shop_items f\xF6r aff\xE4rens sortiment. Verktygen ger bara allm\xE4nt appinneh\xE5ll \u2013 ingen elevdata, den lagras lokalt i elevens webbl\xE4sare.",
  tools: [get_app_overview_default, list_tips_default, suggest_coping_default, list_achievements_default, list_shop_items_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.28.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
